### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by coreh** [antlafarge/ALLoader#4]
What license is this released under? MIT?

**Comment by antlafarge** [comment]
You can use it in a commercial product.
If MIT accepts this, this is MIT licensed ^^

**Comment by AmiralSAS** [comment]
Hello. I'm very happy to learn it's usable in commercial product. 
But because you decided it is MIT just based on the usability in
commercial product.
I have the feeling you are going too fast. 

I suggest you to study carefully the different licences and choose the
ones that suit best to you. 

Imagine you want to change something and you can't because of your
choice of licensing and then have regrets in the future? 

I invite you to take informations on licensing and make a choice you are
sure you won't regret. 

If this is wrong interpretation of me, please just ignore my message. 

bye 

Le 2016-07-18 13:11, antlafarge a écrit : 

> You can use it in a commercial product.
> If MIT accepts this, this is MIT licensed ^^ 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/antlafarge/ALLoader/issues/4#issuecomment-233301652
[2]
